import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/shared/providers";

const inter = Inter({
    subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Уют под ногами",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${inter.className} antialiased bg-[#f5f5f7]`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}